### ISSUE TITLE
float32 write not supported in python api

### ISSUE THREAD

**Issue by wmles** [openPMD/openPMD-api#331] opened 2018-09-05 13:26 UTC
The `3_write_serial.py`-example works with `float64`, and it seems, that `float32` is not supported. The traceback from the exception is: 

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-11-83d8c8e2e8a0> in <module>()
>      42     # TODO implement slicing protocol
>      43     # E[offset[0]:extent[0], offset[1]:extent[1]] = global_data
> ---> 44     rho.store_chunk(offset, extent, global_data)
>      45     print("Stored the whole Dataset contents as a single chunk, " +
>      46           "ready to write content")
> 
> RuntimeError: Datatype 'float32' not known in 'store_chunk'!

to reproduce, paste the following modified example in an ipython shell

```python
    import openPMD
    import numpy as np
    
    
    if __name__ == "__main__":
        # user input: size of matrix to write, default 3x3
        size = 3
    
        # matrix dataset to write with values 0...size*size-1
        global_data = np.arange(size*size, dtype=np.float32)
    
        print("Set up a 2D square array ({0}x{1}) that will be written".format(
            size, size))
    
        # open file for writing
        series = openPMD.Series(
            "../samples/3_write_serial_py.h5",
            openPMD.Access_Type.create
        )
    
        print("Created an empty {0} Series".format(series.iteration_encoding))
    
        print(len(series.iterations))
        rho = series.iterations[1]. \
            meshes["rho"][openPMD.Mesh_Record_Component.SCALAR]
    
        datatype = openPMD.Datatype.FLOAT
        # datatype = openPMD.determineDatatype(global_data)
        extent = [size, size]
        dataset = openPMD.Dataset(datatype, extent)
    
        print("Created a Dataset of size {0}x{1} and Datatype {2}".format(
            dataset.extent[0], dataset.extent[1], dataset.dtype))
    
        rho.reset_dataset(dataset)
        print("Set the dataset properties for the scalar field rho in iteration 1")
    
        # writing fails on already open file error
        series.flush()
        print("File structure has been written")
    
        offset = [0, 0]
        # TODO implement slicing protocol
        # E[offset[0]:extent[0], offset[1]:extent[1]] = global_data
        rho.store_chunk(offset, extent, global_data)
        print("Stored the whole Dataset contents as a single chunk, " +
              "ready to write content")
    
        series.flush()
    print("Dataset content has been fully written")
```

...where I only changed the `dtype=np.double` to `dtype=np.float32` and the `openPMD.Datatype.DOUBLE` to `openPMD.Datatype.FLOAT`
Where the `np.float32` is equivalent to the aliases `np.single`, `"f"`, and maybe more.

The [numpy documentation](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html) makes no distinction between float32 and float64 regarding the compatibility to C types. Might be just an easy to fix bug.

**Software Environment:**
`openpmd-api 0.4.0a` installed via `conda 4.5.2` on piz-daint (SUSE Linux Enterprise Server 12 SP2) for `python 3.6.3` working with `h5py 2.7.0` (how do i get hdf5-version? :))

**Comment by anokfireball** [comment] 2018-09-05 15:18
Hi @wmles!
This same issue has emerged internally for us a few days ago. There are two merged pull requests (#318, #320) that try to address the single precision problem, in correspondence with numpy devs. These were only very recent and no version bump has happened since. As the problem is quite severe considering the HPC environment and related to another current Python PR (#330), we will probably release ```0.4.1a``` as soon as the latter one has been merged.
Until then, the only way to use ```dtype=np.float32``` in the Python API is by building the latest ```dev``` locally.

**Comment by ax3l** [comment] 2018-09-05 16:34
~~I checked the latest `dev` and it looks to me that the `set_chunk` python API suffers from a similar problem as the `set_attribute` we are currently fixing in #330.~~ Will check and provide a fix after that, thx for the detailed report!

Update: uh wait, looks like it's fixed in `dev` already, you were right :)

**Comment by ax3l** [comment] 2018-09-05 16:40
@wmles you can get the `HDF5` version inside `h5py` via: `import h5py; print(h5py.h5.HDF5_VERSION_COMPILED_AGAINST)`

If you installed via `conda`, check:
```bash
conda list | grep hdf5
```

**Comment by ax3l** [comment] 2018-09-17 16:13
Hi @wmles, sorry for the delay in the bug fix. The underlying type system got a full rework so that python attribute writing also works as expected now.

If you update your conda install to the latest version of openPMD-api, version 0.5.0a, this should be fixed:
```bash
conda update -c conda-forge openpmd-api
```

Can you confirm?

**Closed as completed** 2018-09-18 23:06 UTC
Labels: bug, affects latest release, frontend: Python3
