### ISSUE TITLE
Problem to open bp file when an attribute is removed at a certain timestep

### ISSUE THREAD

**Issue by tmsclark** [openPMD/openPMD-api#1212] opened 2022-03-01 11:50 UTC
Good morning,
I have a problem opening a file with the backend bp when I removed attributes at a certain timestep (E_lvl1, B_lvl1...). Indeed, from this timestep i cannot open the following files, this problem happens only with bp backend. I try to use h5 backend and there is no more problem.

To obtain this error, i just open the files with:
```py
import openpmd_api as io
series = io.Series("diags/diag1h5/openpmd_00200.bp", io.Access.read_only)
```

and I obtain this error :
![image](https://user-images.githubusercontent.com/66143812/156162593-aa29981f-1283-417d-90dc-a34ca97ac2fd.png)

I give two files for each backend(h5,bp), one step before the removal and at the step of the removal : 
https://www.transfernow.net/dl/20220301qicEOJPJ

Current work-around: split series manually for read back (before and after these records/variables change).

**Software Environment**
 - version of openPMD-api: 0.14.4
 - installed openPMD-api via: pip
 - name and version of Python implementation: Python 3.9
 - version of HDF5: 1.12.0
 - version of ADIOS2:2.7.1
 - name and version of MPI:

**Comment by ax3l** [comment] 2022-03-06 07:14
@franzpoeschel @tmsclark created two example files. I think this is a problem in the ADIOS2 read logic. Can you take this on, please? :)
Let me know if you have any question on the data file, it's a WarpX one where we have a few constant records at the beginning of a simulation and do not write that record anymore later on (because `B_lvl1` is not part of the simulation anymore after a certain amount of steps).

* BP4: [diag1.tar.gz](https://github.com/openPMD/openPMD-api/files/8192119/diag1.tar.gz) (broken in read)
* HDF5: [diag1h5.zip](https://github.com/openPMD/openPMD-api/files/8192127/diag1h5.zip) (ok)

**Comment by franzpoeschel** [comment] 2022-03-09 16:06
This seems to be a bug in writing, the error also occurs when only reading iteration 60:
```
> openpmd-ls openpmd_00060.bp
Series constructor called with explicit iteration suggests loading a single file with groupBased iteration encoding. Loaded file is fileBased.
openPMD series: openpmd_00060
openPMD standard: 1.1.0
openPMD extensions: 1

data author: unknown
data created: 2022-02-25 18:39:57 +0100
data backend: ADIOS2
generating machine: unknown
generating software: WarpX (version: 21.06-703-g243648035be1-dirty)
generating software dependencies: unknown

number of iterations: 1 (fileBased)
  all iterations: [ADIOS2] Warning: Attribute with name /data/60/fields/E_lvl1/z/value has no type in backend.
[ADIOS2] Warning: Attribute with name /data/60/fields/E_lvl1/z/value has no type in backend.
[~Series] An error occurred: [ADIOS2] Requested attribute (/data/60/fields/E_lvl1/z/value) not found in backend.
[ADIOS2] Warning: Attribute with name /data/60/fields/E_lvl1/z/value has no type in backend.
[~ADIOS2IOHandler] An error occurred: [ADIOS2] Requested attribute (/data/60/fields/E_lvl1/z/value) not found in backend.
An error occurred while opening the specified openPMD series!
[ADIOS2] Requested attribute (/data/60/fields/E_lvl1/z/value) not found in backend.
```

Iteration 60 seems to still contain some incomplete scaffolding for the `E_lvl1` field, but no actual data:
```
> bpls diag1/openpmd_00060.bp/ -ae '.*E_lvl1.*'
  string    /data/60/fields/E_lvl1/axisLabels                    attr
  string    /data/60/fields/E_lvl1/dataOrder                     attr
  string    /data/60/fields/E_lvl1/fieldSmoothing                attr
  string    /data/60/fields/E_lvl1/geometry                      attr
  double    /data/60/fields/E_lvl1/gridGlobalOffset              attr
  double    /data/60/fields/E_lvl1/gridSpacing                   attr
  double    /data/60/fields/E_lvl1/gridUnitSI                    attr
  float     /data/60/fields/E_lvl1/timeOffset                    attr
  double    /data/60/fields/E_lvl1/unitDimension                 attr
  double    /data/60/fields/E_lvl1/x/position                    attr
  double    /data/60/fields/E_lvl1/x/unitSI                      attr
  double    /data/60/fields/E_lvl1/y/position                    attr
  double    /data/60/fields/E_lvl1/y/unitSI                      attr
  double    /data/60/fields/E_lvl1/z/position                    attr
  double    /data/60/fields/E_lvl1/z/unitSI                      attr
```

Related: We are planning to make our reading procedures more lenient and skip incomplete items instead of failing. That's an upcoming new feature however, for the moment there is probably a bug in data creation.

**Comment by ax3l** [comment] 2022-03-16 17:08
the problem is likely in WarpX: we probably use `maxLevel` (maximum possible refinement level) when we loop and declare records. We should use `finestLevel` (currently used, highest refinement level).

Depends on https://github.com/ECP-WarpX/WarpX/pull/2948

**Comment by ax3l** [comment] 2022-03-16 17:46
Fix proposed in WarpX: https://github.com/ECP-WarpX/WarpX/pull/2970

Since this is purely a downstream bug as we introduce more dynamic mesh-refinement capabilities, I will close the issue here and continue tracking in the WarpX pulll request.

Thank you all for your help, the report and triaging support! :)

**Closed as completed by ax3l** 2022-03-16 17:46 UTC
Labels: question, backend: ADIOS2
