### ISSUE TITLE
Copy assignment operator of Attributable does not copy all necessary values

### ISSUE THREAD

**Issue by franzpoeschel** [openPMD/openPMD-api#765] opened 2020-08-17 09:37 UTC
[Copy assignment operator definition](https://github.com/openPMD/openPMD-api/blob/66472782e121d2d233dc8733183003668b91150e/src/backend/Attributable.cpp#L50):
```cpp
Attributable&
Attributable::operator=(Attributable const& a)
{
    if( this != &a )
    {
        Attributable tmp(a);
        std::swap(m_attributes, tmp.m_attributes);
    }
    return *this;
}
```
But the class also has the [following members](https://github.com/openPMD/openPMD-api/blob/66472782e121d2d233dc8733183003668b91150e/include/openPMD/backend/Attributable.hpp#L191):
```cpp
    std::shared_ptr< Writable > m_writable;
    /* views into the resources held by m_writable
     * purely for convenience so code that uses these does not have to go through m_wriable-> */
    AbstractFilePosition* abstractFilePosition;
    AbstractIOHandler* IOHandler;
    Writable* parent;
    bool& dirty;
    bool& written;
```
This means that all code accessing these members, will write to the wrong iteration. The following code triggers the error:
```cpp
#include <openPMD/openPMD.hpp>

#include <cstdlib>
#include <iostream>
#include <memory>
#include <numeric>


using std::cout;
using namespace openPMD;

int
main()
{
    using position_t = double;

    // open file for writing
    Series series( "electrons.bp", Access::CREATE );

    Datatype datatype = determineDatatype< position_t >();
    constexpr unsigned long length = 10ul;
    Extent global_extent = { length };
    Dataset dataset = Dataset( datatype, global_extent );
    std::shared_ptr< position_t > local_data(
        new position_t[ length ],
        []( position_t const * ptr ) { delete[] ptr; } );


    std::unique_ptr< Iteration > iteration_ptr;
    for( size_t i = 0; i < 100; ++i )
    {
        std::cout << "starting to write iteration " << i << std::endl;
        if( iteration_ptr )
        {
            *iteration_ptr = series.iterations[ i ];
        }
        else
        {
            // use copy constructor
            iteration_ptr =
                std::make_unique< Iteration >( series.iterations[ i ] );
        }
        Record electronPositions =
            iteration_ptr->particles[ "e" ][ "position" ];

        std::iota( local_data.get(), local_data.get() + length, i * length );
        for( auto const & dim : { "x", "y", "z" } )
        {
            RecordComponent pos = electronPositions[ dim ];
            pos.resetDataset( dataset );
            pos.storeChunk( local_data, Offset{ 0 }, global_extent );
        }
        iteration_ptr->close();
        // force re-flush of previous iterations
        series.flush();
    }

    return 0;
}
```
Output: 
```
starting to write iteration 0
starting to write iteration 1
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Series] Closed iteration has not been written. This is an internal error.
```

**Comment by ax3l** [comment] 2020-09-03 00:39
Thanks for the great documentation. I can reproduce this.

It's interesting that the attributable does not get the other attributes, since the `Attributable tmp(a);` copies over the other members:
https://github.com/openPMD/openPMD-api/blob/66472782e121d2d233dc8733183003668b91150e/src/backend/Attributable.cpp#L40-L48

But as you wrote, the problem is in `operator=`.

**Comment by ax3l** [comment] 2020-09-05 07:30
Observation: if you `flush()` before the close no error occurs:
```c++
        series.flush();
        iteration_ptr->close();
        // force re-flush of previous iterations
        series.flush();
```

**Comment by ax3l** [comment] 2020-09-05 08:41
Ok, the problem is that the "convenience" members `bool& dirty/written` cannot be re-assigned to a new alias during an `operator=` overwrite. Will transform to pointers or remove them altogether so one goes through the `m_writable` member instead: #769

Alternatively, one could `= delete;` the assignment `operator=` of `Attributable` and `Iteration` altogether. Not sure why we even allow this :grin: :
```c++
            *iteration_ptr = series.iterations[ i ];
```
Only [`7_extended_write_serial.cpp`](https://github.com/openPMD/openPMD-api/blob/fe3c1737e84334cff6172b5db9df22077c22a180/examples/7_extended_write_serial.cpp#L86) has an example on this, which is so brief that I don't really know about its purpose.

**Closed as completed** 2020-09-06 17:48 UTC
Labels: bug, affects latest release, frontend: C++17
