### ISSUE TITLE
Unify auxiliary::Variant and Attribute

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#340] opened 2018-09-11 07:27 UTC
I think it makes sense to tell our `auxiliary::Variant` and the allowed types for it, aka `Attribute`, so we can implement the logic of `getCast< > ()` inside `auxiliary::Variant::get< >()` directly.

https://github.com/openPMD/openPMD-api/pull/337#discussion_r216566489

**Comment by anokfireball** [comment] 2018-09-13 09:19
Dupe of #335.

**Closed as completed by anokfireball** 2018-09-13 09:19 UTC
Labels: refactoring, frontend: C++17
